### ISSUE TITLE
Updating required fields with value constraints does not update validation status.

### ISSUE THREAD

**Issue by adlius** [metadatacenter/cedar-embeddable-editor#102]
![Screenshot from 2024-02-14 11-28-06](https://github.com/metadatacenter/cedar-embeddable-editor/assets/1566880/5d38242b-3337-4351-aafa-aec9e5363cc1)

In the screenshot above, the `Injury Type` field has value constraints and you may type and filter and choose from a list of values. It seems updating this field (e.g. clicking the dropdown list of values, clearing the field manually, clearing the field by clicking the x button) does not refresh validation status of the form.

Here is the json for the template in the screenshot: 
[testing-record.json](https://github.com/metadatacenter/cedar-embeddable-editor/files/14283690/testing-record.json)

**Comment by egyedia** [comment]
Was fixed in release 1.2.1
https://github.com/metadatacenter/cedar-embeddable-editor/commit/06d0b042d573ab482ff3a6b1bcd97ca4c75b2599
