### ISSUE TITLE
Green background is unappealing

### ISSUE THREAD

**Issue by matthewhorridge** [metadatacenter/cedar-embeddable-editor#21]
See this:

<img width="968" alt="image" src="https://github.com/metadatacenter/cedar-embeddable-editor/assets/488607/132fa3a6-e801-43f2-b953-072aa431a435">

Aside from the color, it's visual clutter.  Why do individual fields need borders, backgrounds and drop shadows around them?

Without:

<img width="973" alt="image" src="https://github.com/metadatacenter/cedar-embeddable-editor/assets/488607/f36283f1-8841-4cd9-b32d-01e3e4b7d6cf">

CC'ing @jvendetti for UI expertise and input

**Comment by muakdogan** [comment]
It's helpful to have a border when nested elements have multiple instances, makes it intuitive to which button belongs to which element. Ex:
<img width="1528" alt="Screenshot 2023-07-27 at 10 50 23 AM" src="https://github.com/metadatacenter/cedar-embeddable-editor/assets/19971240/49cc2fde-fbbe-40db-8b48-0e12291810e8">

**Comment by muakdogan** [comment]
Background changed to white but leaving the card view, closing with PR #47. Pls open a new issue for card view if it's a big concern.
