### ISSUE TITLE
Help Text is Tiny

### ISSUE THREAD

**Issue by matthewhorridge** [metadatacenter/cedar-embeddable-editor#23]
e.g. 

<img width="478" alt="image" src="https://github.com/metadatacenter/cedar-embeddable-editor/assets/488607/6d055748-0ddc-4d48-b188-bc1b463cd853">

**Comment by muakdogan** [comment]
Changed and closed with PR #53

**Comment by muakdogan** [comment]
Changed and closed with PR #53
