### ISSUE TITLE
Delete/Clear button in a field needs a focus ring

### ISSUE THREAD

**Issue by matthewhorridge** [metadatacenter/cedar-embeddable-editor#24]
In this screenshot the delete/clear button is focused but it's highly non-obvious.  It needs a focus ring.  When tabbing through fields the focus appears to get lost (until you eventually realize what's happing).

<img width="928" alt="image" src="https://github.com/metadatacenter/cedar-embeddable-editor/assets/488607/d4d6f1dc-b2fd-450f-833f-504c85e7d901">

**Comment by muakdogan** [comment]
Changed and closed with PR #46
