### ISSUE TITLE
White space required between element title and cardinality

### ISSUE THREAD

**Issue by matthewhorridge** [metadatacenter/cedar-embeddable-editor#25]
See this,

<img width="274" alt="image" src="https://github.com/metadatacenter/cedar-embeddable-editor/assets/488607/b8b708e2-6990-461c-9167-b6e6a29f4f82">

There is no space between the words "Subjects" and the opening bracket of the cardinality.

**Comment by muakdogan** [comment]
Done and closed with PR #44
