### ISSUE TITLE
Autocompletion for list field types doesn't work as expected

### ISSUE THREAD

**Issue by matthewhorridge** [metadatacenter/cedar-embeddable-editor#26]
The Autocompletion for lists feels clunky.

The popup does not appear after tabbing to the field when typing.  In the image below I'm trying to type in `en` but all ee just "magically" appears in the field without a popup appearing.

<img width="403" alt="image" src="https://github.com/metadatacenter/cedar-embeddable-editor/assets/488607/82ea1284-9098-445d-a13f-e77ab2cb80c5">

**Comment by muakdogan** [comment]
Fixed and closed with PR #49
