### ISSUE TITLE
Don't autofill dates

### ISSUE THREAD

**Issue by matthewhorridge** [metadatacenter/cedar-embeddable-editor#30]
I noticed that the date fields in my instance have been filled out with the current date.  This shouldn't happen.    Not sure when this happened... perhaps when I tried to save the instance.

<img width="410" alt="image" src="https://github.com/metadatacenter/cedar-embeddable-editor/assets/488607/fc4dc326-ae6a-4c82-9b41-d1f71a8f28cd">

**Comment by muakdogan** [comment]
Fixed and closing with PR  #37
