### ISSUE TITLE
Remove Date field clutter

### ISSUE THREAD

**Issue by matthewhorridge** [metadatacenter/cedar-embeddable-editor#31]
Why does the date field contain, "DateTime is" with a repetion of what's in the field?  "Stored as" also.

<img width="914" alt="image" src="https://github.com/metadatacenter/cedar-embeddable-editor/assets/488607/5fa8c977-b9a9-4460-b579-61769f5e783c">

**Comment by muakdogan** [comment]
Done and closed with PR #40

**Comment by muakdogan** [comment]
Done and closed with PR #40
