### ISSUE TITLE
Floating title on fields is unnecessary

### ISSUE THREAD

**Issue by matthewhorridge** [metadatacenter/cedar-embeddable-editor#33]
For example:

The field in the image below already has a Title, but the floating title is also present.

<img width="374" alt="image" src="https://github.com/metadatacenter/cedar-embeddable-editor/assets/488607/b5350829-2c7e-4588-9a0d-401d81d7e44f">

**Comment by muakdogan** [comment]
Floating labels removed and issue closed with PR #42
