### ISSUE TITLE
The DateTime field value cannot be saved by typing 

### ISSUE THREAD

**Issue by yancao77** [metadatacenter/cedar-embeddable-editor#48]
It can only be saved when selected from the calendar. Furthermore, when saving, the day value is being recorded instead of the year.

<img width="432" alt="Screenshot 2023-07-27 at 12 06 26 PM" src="https://github.com/metadatacenter/cedar-embeddable-editor/assets/131015250/135c473b-54f2-4f74-ab04-143e976385e8">

**Comment by muakdogan** [comment]
Updated and closed with #72  date can only be picked with date time picker, no keyboard entry.
