### ISSUE TITLE
Any update to UI to be expected?

### ISSUE THREAD

**Issue by beepsoft** [metadatacenter/cedar-embeddable-editor#9]
Attila Egyed mentioned in this video https://youtu.be/-Q0kLtsWN48?t=181 that the UI would be updated so that it would be more compact. He also mentioned that the editor doesn't handle all the fields a CEDAR template provides.

So, can you please tell me how complete the embeddable editor is, and whether an updated UI can be expected any time soon?

Thanks!

**Comment by martinjoconnor** [comment]
Sorry - missed this. There have been several recent updates to the embeddable editor. Try to latest release. It should now handle all fields.
